version: '3'

services:
  webrtc-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./server_recordings:/app/server_recordings
      - ./static:/app/static
    restart: unless-stopped 